### ISSUE TITLE
Do a new release

### ISSUE THREAD

**Issue by halkeye** [withspectrum/danger-plugin-labels#74]
Latest release is unusable because of replaceAllLabels (https://github.com/withspectrum/danger-plugin-labels/commit/913f0e574ee70a624d09c6f1294fb69b72f55580) fix

```
Unable to evaluate the Dangerfile
 TypeError: api.issues.replaceAllLabels is not a function
    at /home/halkeye/go/src/github.com/halkeye/test-danger-js/node_modules/danger-plugin-labels/dist/index.js:99:26
    at Generator.next (<anonymous>)
    at fulfilled (/home/halkeye/go/src/github.com/halkeye/test-danger-js/node_modules/danger-plugin-labels/dist/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Can you push a new release?

**Comment by Sly777** [comment]
Same error unfortunately :(

**Comment by thlmenezes** [comment]
Same error still, I believe there are no intentions to further maintain this library from the author

**Comment by thlmenezes** [comment]
If anyone wants to pick up this and make a PR here's some documentation around what is currently available:
- [GitHubDSL](https://danger.systems/js/reference.html#GitHub)
- [`danger.github.api.issues`](https://octokit.github.io/rest.js/v18#issues)

- [`danger-plugin-labels/src/index.ts:125`](https://github.com/withspectrum/danger-plugin-labels/blob/c143b95c692d9f1cff0e3c2c81278ad7ccd448f9/src/index.ts#L125)

Could solve this later.

**Comment by thlmenezes** [comment]
Appears the cause is a name change to issues API in v17 forward: replaceLabels -> replaceAllLabels -> setLabels
https://github.com/octokit/rest.js/commit/b4ab0db04fd66eb02a10deabd2149ff82b43ac78

**Comment by thlmenezes** [comment]
@mxstbr is there an interest in maintaining this repo?
